Feature/1003 add container scans (#103)
* Adding docker image scanning to CircleCI config

* clean up todos in circleCI config

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,5 +1,7 @@
 # CircleCI v2.1 Config
 version: 2.1
+orbs:
+  anchore: anchore/anchore-engine@1.6.0
 
 defaults_Dependencies: &defaults_Dependencies |
   apk --no-cache add git
@@ -151,6 +153,7 @@ executors:
     docker: 
       - image: hypnoglow/kubernetes-helm
 
+
 jobs:
   setup:
     executor: default-docker
@@ -164,9 +167,6 @@ jobs:
       - run:
           name: Access npm folder as root
           command: cd $(npm root -g)/npm
-      #      - run:
-      #          name: Install interledgerjs/five-bells-ledger-api-tests
-      #          command: npm install github:interledgerjs/five-bells-ledger-api-tests
       - run:
           name: Update NPM install
           command: npm install
@@ -258,81 +258,6 @@ jobs:
       - store_test_results:
           path: ./test/results
 
-  #  test-functional:
-  #    machine: true
-  #    <<: *defaults_working_directory
-  #    steps:
-  #      - run:
-  #          name: Add the Postgres 9.6 binaries to the path.
-  #          command: echo "/usr/lib/postgresql/9.6/bin/:$PATH" >> $BASH_ENV
-  #      - run:
-  #          name: Install Docker Compose
-  #          command: |
-  #            curl -L https://github.com/docker/compose/releases/download/1.11.2/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
-  #            chmod +x ~/docker-compose
-  #            mv ~/docker-compose /usr/local/bin/docker-compose
-  #      - checkout
-  #      - restore_cache:
-  #          key: dependency-cache-{{ checksum "package.json" }}
-  #      - run:
-  #          name: Create dir for test results
-  #          command: mkdir -p ./test/results
-  #      - run:
-  #          name: Execute functional tests
-  #          command: npm -s run test:functional
-  #      - store_artifacts:
-  #          path: ./test/results
-  #          prefix: test
-  #      - store_test_results:
-  #          path: ./test/results
-
-  #   test-spec:
-  #     machine: true
-  #     # <<: *defaults
-  #     steps:
-  #     #   - run:
-  #     #       name: Install general dependencies
-  #     #       command: *defaultDependencies
-  #     #   - run:
-  #     #       name: Add the Postgres 9.6 binaries to the path.
-  #     #       command: apk --no-cache add postgresql-client
-  #     #   - setup_remote_docker
-  #     #   - run:
-  #     #       name: Add docker
-  #     #       command: apk --no-cache add docker
-  #     #   - run:
-  #     #       name: Add docker compose
-  #     #       command: |
-  #     #         apk --no-cache add py-pip
-  #     #         pip install docker-compose
-  #     #   - run:
-  #     #       name: Install Docker Compose
-  #     #       command: |
-  #     #         curl -L https://github.com/docker/compose/releases/download/1.8.0/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose; chmod +x /usr/local/bin/docker-compose
-  #       - run:
-  #           name: Add the Postgres 9.6 binaries to the path.
-  #           command: echo "/usr/lib/postgresql/9.6/bin/:$PATH" >> $BASH_ENV
-  #       - run:
-  #           name: Install Docker Compose
-  #           command: |
-  #             curl -L https://github.com/docker/compose/releases/download/1.11.2/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
-  #             chmod +x ~/docker-compose
-  #             mv ~/docker-compose /usr/local/bin/docker-compose
-  #       - checkout
-  #       - restore_cache:
-  #           key: dependency-cache-{{ checksum "package.json" }}
-  #       - run:
-  #           name: Create dir for test results
-  #           command: mkdir -p ./test/results
-  #       - run:
-  #           name: Execute unit tests
-  #           command: npm -s run test:spec
-  #       - store_artifacts:
-  #           path: ./test/results
-  #           prefix: test
-  #       - store_test_results:
-  #           path: ./test/results
-
   vulnerability-check:
     executor: default-docker
     steps:
@@ -398,7 +323,6 @@ jobs:
 
   build-hotfix:
     executor: default-machine
-    # <<: *default_env
     steps:
       - checkout
       - run:
@@ -418,19 +342,28 @@ jobs:
 
   build:
     executor: default-machine
-    # <<: *default_env
     steps:
       - checkout
       - run:
           <<: *defaults_environment
       - run:
-          name: setup environment vars for LATEST release
-          command: |
-            echo 'export RELEASE_TAG=$RELEASE_TAG_PROD' >> $BASH_ENV
-      - run:
-          <<: *defaults_build_docker_login
-      - run:
           <<: *defaults_build_docker_build
+      - run:
+          name: save docker image to workspace
+          command: docker save -o /tmp/docker-image.tar $DOCKER_ORG/$CIRCLE_PROJECT_REPONAME:$CIRCLE_TAG
+      - persist_to_workspace:
+          root: /tmp
+          paths:
+            - ./docker-image.tar
+      
+  license-scan:
+    executor: default-machine
+    steps:
+      - attach_workspace:
+          at: /tmp
+      - run:
+          name: Load the pre-built docker image from workspace
+          command: docker load -i /tmp/docker-image.tar
       - run:
           <<: *defaults_license_scanner
       - run:
@@ -439,8 +372,69 @@ jobs:
       - store_artifacts:
           path: /tmp/license-scanner/results
           prefix: licenses
+
+  image-scan:
+    executor: anchore/anchore_engine
+    steps:
+      - setup_remote_docker
+      - checkout
+      - attach_workspace:
+          at: /tmp
       - run:
-          <<: *defaults_build_docker_build_release
+          name: Load the pre-built docker image from workspace
+          command: docker load -i /tmp/docker-image.tar
+      - anchore/analyze_local_image:
+          dockerfile_path: ./Dockerfile
+          image_name: ${DOCKER_ORG}/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_TAG}
+          policy_bundle_file_path: .circleci/.anchore/policy_bundle.json
+          # Anchore bug: if policy_failure is `true`, reports don't get written - we manually check for 
+          policy_failure: false
+          timeout: '500'
+      - run:
+          name: Evaluate Failures.
+          command: |
+            if [[ ! $(which jq) ]]; then
+              (set +o pipefail; apk add jq || apt-get install -y jq || yum install -y jq)
+            fi
+            if [[ $(ls anchore-reports/*content-os*.json 2> /dev/null) ]]; then
+              printf "\n%s\n" "The following OS packages are installed:"
+              jq '[.content | sort_by(.package) | .[] | {package: .package, version: .version}]' anchore-reports/*content-os*.json
+            fi
+            if [[ $(ls anchore-reports/*vuln*.json 2> /dev/null) ]]; then
+              printf "\n%s\n" "The following vulnerabilities were found:"
+              jq '[.vulnerabilities | group_by(.package) | .[] | {package: .[0].package, vuln: [.[].vuln]}]' anchore-reports/*vuln*.json
+            fi
+
+            # Check the status of the policy.json for whether or not our tests failed
+            failCount=$(cat anchore-reports/*policy*.json | grep '\"status\": \"fail\"' | wc -l)
+            if [ $failCount -gt 0 ]; then
+              echo "Failed with a policy failure count of: ${failCount}"
+              # TODO: Enable this when we want to increase the strictness of our security policies
+              # exit 1
+            fi
+
+      - store_artifacts:
+          path: anchore-reports
+
+  publish:
+    executor: default-machine
+    steps:
+      - checkout
+      - attach_workspace:
+          at: /tmp
+      - run:
+          name: Load the pre-built docker image from workspace
+          command: docker load -i /tmp/docker-image.tar
+      - run:
+          <<: *defaults_build_docker_login
+      - run:
+          name: setup environment vars for LATEST release
+          command: |
+            echo 'export RELEASE_TAG=$RELEASE_TAG_PROD' >> $BASH_ENV
+      - run:
+          name: Re-tag pre built image
+          command: |
+            docker tag $DOCKER_ORG/$CIRCLE_PROJECT_REPONAME:$CIRCLE_TAG $DOCKER_ORG/$CIRCLE_PROJECT_REPONAME:$RELEASE_TAG
       - run:
           <<: *defaults_build_docker_publish
       - run:
@@ -526,7 +520,7 @@ workflows:
           context: org-global
           filters:
             tags:
-              only: /.*/
+              only: /v[0-9]+(\.[0-9]+)*/
             branches:
               ignore:
                 - /feature*/
@@ -593,18 +587,8 @@ workflows:
             - test-unit
             - test-coverage
             - test-integration
-          #            - test-functional
-          #            - test-spec
-          filters:
-            tags:
-              only: /v[0-9]+(\.[0-9]+)*\-snapshot/
-            branches:
-              ignore:
-                - /.*/
-      - deploy-snapshot:
-          context: org-global
-          requires:
-            - build-snapshot
+            - vulnerability-check
+            - audit-licenses
           filters:
             tags:
               only: /v[0-9]+(\.[0-9]+)*\-snapshot/
@@ -618,8 +602,6 @@ workflows:
             - test-unit
             - test-coverage
             - test-integration
-          #            - test-functional
-          #            - test-spec
             - vulnerability-check
             - audit-licenses
           filters:
@@ -635,8 +617,6 @@ workflows:
             - test-unit
             - test-coverage
             - test-integration
-          #            - test-functional
-          #            - test-spec
             - vulnerability-check
             - audit-licenses
           filters:
@@ -645,7 +625,18 @@ workflows:
             branches:
               ignore:
                 - /.*/
-      - deploy:
+      - license-scan:
+          context: org-global
+          requires:
+            - build
+          filters:
+            tags:
+              only: /v[0-9]+(\.[0-9]+)*/
+            branches:
+              only: /feature\/1003.*/
+              ignore:
+                - /.*/
+      - image-scan:
           context: org-global
           requires:
             - build
@@ -654,3 +645,35 @@ workflows:
               only: /v[0-9]+(\.[0-9]+)*/
             branches:
               ignore:
+                - /.*/
+      - publish:
+          context: org-global
+          requires:
+            - license-scan
+            - image-scan
+          filters:
+            tags:
+              only: /v[0-9]+(\.[0-9]+)*/
+            branches:
+              ignore:
+                - /.*/
+      - deploy:
+          context: org-global
+          requires:
+            - publish
+          filters:
+            tags:
+              only: /v[0-9]+(\.[0-9]+)*/
+            branches:
+              ignore:
+                - /.*/
+      - deploy-snapshot:
+          context: org-global
+          requires:
+            - build-snapshot
+          filters:
+            tags:
+              only: /v[0-9]+(\.[0-9]+)*\-snapshot/
+            branches:
+              ignore:
+                - /.*/
